### ISSUE TITLE
Closed Frame

### ISSUE THREAD

**Issue by HoreaOros** [HoreaOros/OOP2022Spring#1]
In proiectul Bars ar trebui modificata clasa Frame in asa fel incat sa se deseneze ceea ce ii spune numele - adica un chenar complet inchis din toate cele 4 parti (adica un dreptunghi).

**Comment by albertotirla** [comment]
pentru a desena un dreptunghi inchis, ar trebui sa se faca niste modificari codului curent, anume:

* o clasa noua care este responsabila pentru desenarea unei linii ce contine o bara verticala, `length-2` spatii si o alta bara verticala. Un nume sugestiv poate fi "DelimitedWhiteSpace"
* o noua clasa ClosedFrame care realizeaza desenul, in felul urmator:
  * un `HorisontalBar` de dimensiune length
  * instantierea a `height-2` obiecte de tip `DelimitedWhiteSpace`, probabil cu o bucla de tip `for`
  * inca un `HorisontalBar` de dimensiune length
